### ISSUE TITLE
Better handle glitch tracing in CollectAudioLogs

### ISSUE THREAD

**Issue by garydan42** [microsoft/audio#6]
Today using CollectAudioLogs for glitch tracing requires knowing not to enable time travel tracing, and that additional system information isn't required. Also, because glitch logging is included for all tracing, audio logging is limited to 30 to 60 seconds of data (stream creation logging ages out very quickly).

So, it may be useful to define a CollectAudioGlitchLogs.cmd, which launches CollectAudioLogs with some additional parameters so that we better target collection. Alternatively, the CollectAudioLogs could ask the user if the log collection is for diagnosing glitches.

**Comment by mvaneerde** [comment]
I suggest three parameters and three .cmd files:

Parameters
1. -diagnostics
2. -repro
3. -timetraveltrace

Command files
1. I-cannot-recreate.cmd - passes -diagnostics
4. I-can-recreate.cmd - passes -diagnostics, -repro, and -timetraveltrace
5. I-can-recreate-audio-glitch.cmd - passes -diagnostics and -repro

People who want other combinations can call the .ps1 directly

**Comment by mvaneerde** [comment]
Fixed with PR #10
